### ISSUE TITLE
No UTF-8

### ISSUE THREAD

**Issue by kimberly-moors** [kimberly-moors/Facebook-emoticons#1]
Bij het bewerken van mijn dataset krijg ik regelmatig de volgende code: no UTF-8.
Ik ben door mijn volledige dataset gegaan, via de print x.head(getal) methode en heb de no UTF-8 zinnen verwijderd. 
Nu bij de volgdende stap krijg ik opnieuw de volgende melding.

**Comment by stephantul** [comment]
Hallo Kimberly,

Dit kan je oplossen door [deze regel](https://github.com/kimberly-moors/Facebook-emoticons/blob/master/Data.py#L9) te veranderen in: 
```
dataset= open ("D:\Thesis\mypersonality_final\mypersonality_final2.csv", encoding="latin-1")
```
Er zijn daarna nog andere fouten, maar dan heb je dit probleem tenminste niet meer.

**Comment by kimberly-moors** [comment]
Hey Stephan,
Ik heb de regel veranderd. Helaas is het probeem in mijn code hierbij nog steeds hetzelfde. In de stap: countvectorizer kan ik namelijk nog steeds niet door mijn volledige dataset laten lopen zonder op een UTF8 code probleem te stuiten. In mijn trainingsdata geraak ik tot rij 1735. Bij mijn testset geraak ik tot rij 133.



vec=CountVectorizer()
Z=vec.fit_transform(testset['STATUS'].head(133))    															#probleem = geen utf-code
features= (pd.DataFrame(Z.toarray(),columns=vec.get_feature_names()))
print(features)

**Comment by stephantul** [comment]
Dit stukje code werkt bij mij (bij jou is het pad naar de file anders)
```python
import csv
import pandas as pd
import sklearn as sk
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer


if __name__ == "__main__":

    file = open("mypersonality_final2.csv", encoding="latin-1")
    dataset = pd.read_csv(file)
    X = dataset.loc[:, ['STATUS', 'cEXT']]
    y = dataset.index

    # Count Vectorizer features
    vec = CountVectorizer()
    Z = vec.fit_transform(X['STATUS'])  
    features = (pd.DataFrame(Z.toarray(), columns=vec.get_feature_names()))
```

**Comment by stephantul** [comment]
Ik zie ook dat de code die je hierboven gepost hebt niet in de repository zit. Kan je je laatste veranderingen eens committen en pushen? Dan weet ik beter waar het vast loopt.

**Comment by kimberly-moors** [comment]
Ok, zal ik doen zodra ik klaar ben met mijn dataframe. In ieder geval bedankt voor uw hulp.

**Comment by kimberly-moors** [comment]
Ik heb mijn code ge-updated. Helaas kom ik nog dezelfde error tegen

**Comment by stephantul** [comment]
Ok, ik krijg je error niet gereproduceerd. Bij mij werkt alles naar behoren. Ik zie dat je een oude versie van sklearn gebruikt. 
Misschien ligt het daar aan. Kan je je sklearn eens volledig up-to-date maken? Dit doe je door `pip install sklearn --upgrade` in je console in te voeren. 

Ik neem aan dat je python 3 gebruikt. Kan je dit bevestigen?

**Comment by kimberly-moors** [comment]
Ik gebruik inderdaad Python3 en heb mijn sklearn net ge-updated. Bij mijn count vectorizer gaat het nu al beter (ik geraak tot 1741) maar geraak er nog steeds niet door zonder fout melding.

Mijn trainingset en testset kan ik nu echter niet meer runnen. Daar loopt het in de eerste 10 rijen al mis.
Er zijn nu twee waarschuwingen die ik krijg:
`UnicodeEncodeError: 'charmap' codec can't encode character '\x92' in position 977: character maps to <undefined>`

of 
`UnicodeError: no utf-8`

**Comment by stephantul** [comment]
Ok, dat is al goed. Probeer ook eens je pandas op dezelfde manier te updaten. 
Op welke regel  van je huidige code crasht het huidige script? Op zich zou het al eerder moeten crashen als er een fout is tijdens het lezen van de data.

**Comment by stephantul** [comment]
Probeer eens met de encoding `Windows-1251`? Misschien werkt dat. Bij mij werken `latin-1` en `Windows-1251` allebei.

**Comment by kimberly-moors** [comment]
Ik heb het volledige systeem ge-updated naar alle recentste versies, inclusief Pandas.
Bij het inlezen van de data geeft hij geen fout weer. Wanneer de data gesplitst wordt lopen zowel de testset als de trainingset vast.
de trainingset op regel 17:
`	print(trainingset.head(17))`
en de testset op regel 7:
`	print(testset.head(7))`
in mijn Countvectorizer zie ik verbetering en loopt hij vast op 1736: 
`	vec=CountVectorizer()`
`	Z=vec.fit_transform(trainingset['STATUS'].head(1736))`
`	features= (pd.DataFrame(Z.toarray(), columns=vec.get_feature_names()))`
`	print(features)`

Kan het dat de fout bij train test split zit?

**Comment by stephantul** [comment]
Ok, ik denk dat het probleem is dat je de data print naar de console. Kan je dat bevestigen? Loopt het nog steeds vast als je je print statements weg haalt?

**Comment by kimberly-moors** [comment]
Ik werk vanuit Sublime text

**Comment by stephantul** [comment]
Ok, maar als je `print()` aanroept, dan print je data nog steeds naar een soort van buffer (dat zou ik een console noemen), ook al zit die in sublime text. Is het het aanroepen van print dat er voor zorgt dat je programma crasht?

**Comment by kimberly-moors** [comment]
Zonder het print commando krijg ik geen foutmeldingen maar doet hij natuurlijk ook niets

**Comment by stephantul** [comment]
Dat is denk ik niet juist. Het `print` commando heeft geen verder causaal effect op je programma, dus een programma zonder `print` statements geeft exact hetzelfde resultaat als hetzelfde programma mét `print` statements (met uitzondering van het printen natuurlijk.) 

Dus je kan gewoon je experimenten runnen zonder print te gebruiken, denk ik, en de resultaten daarna interpreteren.
Als je per sé je data wilt zien, of lezen, dan kan je het best de regels die je wilt lezen naar een file schrijven.

Je kan het ook oplossen door in je sublime text (als je sublime text 3 gebruikt) je build environment aan te passen, zie [hier](https://stackoverflow.com/questions/39576308/printing-utf-8-in-python-3-using-sublime-text-3)
Ik gebruik zelf geen sublime text, dus daar weet ik verder weinig van.

**Comment by kimberly-moors** [comment]
Ok hartelijk bedankt. Met deze was ik al heel lang bezig.
