### ISSUE TITLE
2 cijfers vermist

### ISSUE THREAD

**Issue by kimberly-moors** [kimberly-moors/Facebook-emoticons#2]
Bij het verdelen van mijn data in een trainingset en een hold out set verdwijnen er twee gegevens maar ik weet niet hoe of waar. 

Mijn twee nieuwe datasets bevatten samen de totale dataset en er zijn geen nietgemarkeerde labels. Toch wanneer ik de balans check tussen introvert en extrovert mis ik twee gegevens.

**Comment by stephantul** [comment]
Kan je dit reproduceren met de huidige code, of is dit issue opgelost? Als ik `len(X1)` en `len(X2)` in je script optel krijg ik `len(X)` (9910) terug. Voor de labels idem, je hebt 9910 labels ('n': 5700, 'y': 4210). Als ik `y1` en `y2` optel, dan krijg ik 9910 labels, met dezelfde proportie.

**Comment by kimberly-moors** [comment]
Dank u Stephan.
