### ISSUE TITLE
Het toevoegen van features aan mijn dataset

### ISSUE THREAD

**Issue by kimberly-moors** [kimberly-moors/Facebook-emoticons#5]
Nadat de labels gemaakt zijn. Moeten de features ook nog toegevoegd worden aan de dataset.
(LWIC, Count Vectorizer, Emoji's)

Hoe voeg ik mijn sparse matrix van Count Vectorizer aan mijn datatabel toe?

**Comment by walterdaelemans** [comment]
Je kan de sparse array als X gebruiken en de label encoded klassen als y.

FeatureUnion voor combineren van feature sets
https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.FeatureUnion.html#sklearn.pipeline.FeatureUnion

**Comment by kimberly-moors** [comment]
Bij het implementeren van FeatureUnion werkt Count Vectorizer, DictFeaturizer echter niet aangezien deze geen fit_transform doet.
```
#feature pipeline
	estimators=[('vec', CountVectorizer()), ('dict', DictFeaturizer(trainingset))]
	pip=FeatureUnion(estimators)
	pipy = pip.fit(trainingset, y1)
```

> TypeError: All estimators should implement fit and transform. '<dictfeaturizer.DictFeaturizer object at 0x0000025B4593BB38>' (type <class 'dictfeaturizer.DictFeaturizer'>) doesn't

**Comment by walterdaelemans** [comment]
Bedoel je niet DictVectorizer te gebruiken in plaats van DictFeaturizer? (Die laatste is om distributie van liwc features over documenten te berekenen).
