### ISSUE TITLE
LIWC

### ISSUE THREAD

**Issue by kimberly-moors** [kimberly-moors/Facebook-emoticons#6]
De toepassing van de Dictfeaturizer loopt vast in rij 29 voor de trainingset en in rij 110 voor de testset. De volgende fout word gegeven: 

```
sre_constants.error: missing ), unterminated subpattern at position 445
sre_constants.error: missing ), unterminated subpattern at position 12743
sre_constants.error: unbalanced parenthesis at position 14740
```

**Comment by stephantul** [comment]
Je volgt de instructies voor `DictFeaturizer` niet. Die verwacht namelijk niet de trainingdata als input, maar een dictionary van termen (zoals LIWC.) Ik weet niet of je hier de `DictVectorizer` (uit sklearn) wilt gebruiken, of daadwerkelijk de `DictFeaturizer` wilt toepassen.
